// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    escrow
    (
        init => init
        upgrade => upgrade
        createOffer => create_offer
        cancelOffer => cancel_offer
        acceptOffer => accept_offer
        getCreatedOffers => get_created_offers
        getWantedOffers => get_wanted_offers
        getOffer => offers
        getLastOfferId => last_offer_id
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
