// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    escrow
    (
        init => init
        upgrade => upgrade
        createOffer => create_offer
        cancelOffer => cancel_offer
        acceptOffer => accept_offer
        getCreatedOffers => get_created_offers
        getWantedOffers => get_wanted_offers
        getUserBalance => user_balance
        created_offers => created_offers
        wanted_offers => wanted_offers
        offers => offers
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
